sonar.projectKey=mrTelnor_python-project-83
sonar.organization=mrtelnor

sonar.sources=page_analyzer
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=docs/**,**/__pycache__/**,.venv/**
