name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pytest:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
      - uses: astral-sh/setup-uv@v3
      - run: uv sync
      - name: Run tests with coverage
        run: uv run pytest --cov=page_analyzer --cov-report=xml --cov-report=term
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 1

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          fetch-depth: 0
      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-xml
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602  # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
